# Generated by Django 4.0.6 on 2022-08-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_Title', models.CharField(max_length=200, verbose_name='Content Note')),
                ('note_description', models.CharField(max_length=255, verbose_name='Content Note')),
                ('user_creator', models.CharField(max_length=150, null=True, verbose_name='User Create Note')),
                ('finished_note', models.BooleanField(verbose_name='Finished Task')),
            ],
        ),
    ]
