# Generated by Django 4.0.6 on 2022-08-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_description',
            field=models.TextField(max_length=255, verbose_name='Content Note'),
        ),
    ]
